version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: webapi/Dockerfile
    command: ./rms run
    ports:
      - 8081:8080
    networks:
      - backend
    env_file:
      - ./.env.dev
    volumes:
      - ./Configuration/Parameter:/rmsConfig:ro
      - ./LogHere:/rmsLog
    secrets:
      - SmsSE
      - DbSE
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rmsu
      - POSTGRES_PASSWORD=rmsp
      - POSTGRES_DB=rms_db
    networks:
      - backend
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend

volumes:
  postgres_data:

secrets:
  SmsSE:
    file: ./Configuration/Security/sms.yaml
  DbSE:
    file: ./Configuration/Security/database.yaml

networks:
#  frontend:
  backend:
