PostgreSQL:
  host: rms-pg
  port: 5432
  user: rms
  password: 123456
  dbname: rms_db
  sslmode: disable
#  "host=ras-pg user=postgres password=%s dbname=ras sslmode=disable"

Redis:
  host: 'rms-redis:6379'
  password: 234567