PostgreSQL:
  host: 192.168.10.41
  port: 5432
  user: rmsu
  password: rmsp
  dbname: rms_db
  sslmode: disable
#  "host=ras-pg user=postgres password=%s dbname=ras sslmode=disable"

Redis:
  host: 'rms-redis:6379'
  password: 234567