PostgreSQL:
  host: db
  port: 5432
  user: rmsu
  password: rmsp
  dbname: rms_db
  sslmode: disable
#  "host=ras-pg user=postgres password=%s dbname=ras sslmode=disable"

Redis:
  host: 'redis:6379'
#  password: rmspr

#  docker run --name rmsdb -e POSTGRES_USER=rmsu -e POSTGRES_PASSWORD=rmsp -e POSTGRES_DB=rms_db -d -p 5432:5432 postgres
# docker run -p 6379:6379 -v redis.conf:/usr/local/etc/redis/redis.conf --name myredis -d --rm redis redis-server /usr/local/etc/redis/redis.conf