// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduling.proto

package resScheduling

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SchedulingCGpuRequest struct {
	ProjectID            int64    `protobuf:"varint,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	CgpuType             int64    `protobuf:"varint,2,opt,name=cgpuType,proto3" json:"cgpuType,omitempty"`
	NodesAfter           []int64  `protobuf:"varint,3,rep,packed,name=nodesAfter,proto3" json:"nodesAfter,omitempty"`
	CtrlID               int64    `protobuf:"varint,4,opt,name=ctrlID,proto3" json:"ctrlID,omitempty"`
	CtrlCN               string   `protobuf:"bytes,5,opt,name=ctrlCN,proto3" json:"ctrlCN,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchedulingCGpuRequest) Reset()         { *m = SchedulingCGpuRequest{} }
func (m *SchedulingCGpuRequest) String() string { return proto.CompactTextString(m) }
func (*SchedulingCGpuRequest) ProtoMessage()    {}
func (*SchedulingCGpuRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb732522b6cbe36, []int{0}
}

func (m *SchedulingCGpuRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulingCGpuRequest.Unmarshal(m, b)
}
func (m *SchedulingCGpuRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulingCGpuRequest.Marshal(b, m, deterministic)
}
func (m *SchedulingCGpuRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulingCGpuRequest.Merge(m, src)
}
func (m *SchedulingCGpuRequest) XXX_Size() int {
	return xxx_messageInfo_SchedulingCGpuRequest.Size(m)
}
func (m *SchedulingCGpuRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulingCGpuRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulingCGpuRequest proto.InternalMessageInfo

func (m *SchedulingCGpuRequest) GetProjectID() int64 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

func (m *SchedulingCGpuRequest) GetCgpuType() int64 {
	if m != nil {
		return m.CgpuType
	}
	return 0
}

func (m *SchedulingCGpuRequest) GetNodesAfter() []int64 {
	if m != nil {
		return m.NodesAfter
	}
	return nil
}

func (m *SchedulingCGpuRequest) GetCtrlID() int64 {
	if m != nil {
		return m.CtrlID
	}
	return 0
}

func (m *SchedulingCGpuRequest) GetCtrlCN() string {
	if m != nil {
		return m.CtrlCN
	}
	return ""
}

type SchedulingStorageRequest struct {
	ProjectID             int64    `protobuf:"varint,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	StorageSizeAfter      int64    `protobuf:"varint,2,opt,name=storageSizeAfter,proto3" json:"storageSizeAfter,omitempty"`
	StorageAllocInfoAfter string   `protobuf:"bytes,3,opt,name=storageAllocInfoAfter,proto3" json:"storageAllocInfoAfter,omitempty"`
	CtrlID                int64    `protobuf:"varint,4,opt,name=ctrlID,proto3" json:"ctrlID,omitempty"`
	CtrlCN                string   `protobuf:"bytes,5,opt,name=ctrlCN,proto3" json:"ctrlCN,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SchedulingStorageRequest) Reset()         { *m = SchedulingStorageRequest{} }
func (m *SchedulingStorageRequest) String() string { return proto.CompactTextString(m) }
func (*SchedulingStorageRequest) ProtoMessage()    {}
func (*SchedulingStorageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb732522b6cbe36, []int{1}
}

func (m *SchedulingStorageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulingStorageRequest.Unmarshal(m, b)
}
func (m *SchedulingStorageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulingStorageRequest.Marshal(b, m, deterministic)
}
func (m *SchedulingStorageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulingStorageRequest.Merge(m, src)
}
func (m *SchedulingStorageRequest) XXX_Size() int {
	return xxx_messageInfo_SchedulingStorageRequest.Size(m)
}
func (m *SchedulingStorageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulingStorageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulingStorageRequest proto.InternalMessageInfo

func (m *SchedulingStorageRequest) GetProjectID() int64 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

func (m *SchedulingStorageRequest) GetStorageSizeAfter() int64 {
	if m != nil {
		return m.StorageSizeAfter
	}
	return 0
}

func (m *SchedulingStorageRequest) GetStorageAllocInfoAfter() string {
	if m != nil {
		return m.StorageAllocInfoAfter
	}
	return ""
}

func (m *SchedulingStorageRequest) GetCtrlID() int64 {
	if m != nil {
		return m.CtrlID
	}
	return 0
}

func (m *SchedulingStorageRequest) GetCtrlCN() string {
	if m != nil {
		return m.CtrlCN
	}
	return ""
}

type SchedulingReply struct {
	ProjectID            int64    `protobuf:"varint,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	CpuNodesAcquired     int64    `protobuf:"varint,2,opt,name=cpuNodesAcquired,proto3" json:"cpuNodesAcquired,omitempty"`
	GpuNodesAcquired     int64    `protobuf:"varint,3,opt,name=gpuNodesAcquired,proto3" json:"gpuNodesAcquired,omitempty"`
	StorageSizeAcquired  int64    `protobuf:"varint,4,opt,name=storageSizeAcquired,proto3" json:"storageSizeAcquired,omitempty"`
	StorageAllocInfo     string   `protobuf:"bytes,5,opt,name=storageAllocInfo,proto3" json:"storageAllocInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchedulingReply) Reset()         { *m = SchedulingReply{} }
func (m *SchedulingReply) String() string { return proto.CompactTextString(m) }
func (*SchedulingReply) ProtoMessage()    {}
func (*SchedulingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb732522b6cbe36, []int{2}
}

func (m *SchedulingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulingReply.Unmarshal(m, b)
}
func (m *SchedulingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulingReply.Marshal(b, m, deterministic)
}
func (m *SchedulingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulingReply.Merge(m, src)
}
func (m *SchedulingReply) XXX_Size() int {
	return xxx_messageInfo_SchedulingReply.Size(m)
}
func (m *SchedulingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulingReply.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulingReply proto.InternalMessageInfo

func (m *SchedulingReply) GetProjectID() int64 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

func (m *SchedulingReply) GetCpuNodesAcquired() int64 {
	if m != nil {
		return m.CpuNodesAcquired
	}
	return 0
}

func (m *SchedulingReply) GetGpuNodesAcquired() int64 {
	if m != nil {
		return m.GpuNodesAcquired
	}
	return 0
}

func (m *SchedulingReply) GetStorageSizeAcquired() int64 {
	if m != nil {
		return m.StorageSizeAcquired
	}
	return 0
}

func (m *SchedulingReply) GetStorageAllocInfo() string {
	if m != nil {
		return m.StorageAllocInfo
	}
	return ""
}

///////////////////////////////////////////////////////////
type QueryTreeRequest struct {
	ProjectID            int64    `protobuf:"varint,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	CgpuType             int64    `protobuf:"varint,2,opt,name=cgpuType,proto3" json:"cgpuType,omitempty"`
	QueryType            int64    `protobuf:"varint,3,opt,name=queryType,proto3" json:"queryType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTreeRequest) Reset()         { *m = QueryTreeRequest{} }
func (m *QueryTreeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTreeRequest) ProtoMessage()    {}
func (*QueryTreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb732522b6cbe36, []int{3}
}

func (m *QueryTreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTreeRequest.Unmarshal(m, b)
}
func (m *QueryTreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTreeRequest.Marshal(b, m, deterministic)
}
func (m *QueryTreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTreeRequest.Merge(m, src)
}
func (m *QueryTreeRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTreeRequest.Size(m)
}
func (m *QueryTreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTreeRequest proto.InternalMessageInfo

func (m *QueryTreeRequest) GetProjectID() int64 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

func (m *QueryTreeRequest) GetCgpuType() int64 {
	if m != nil {
		return m.CgpuType
	}
	return 0
}

func (m *QueryTreeRequest) GetQueryType() int64 {
	if m != nil {
		return m.QueryType
	}
	return 0
}

type QueryTreeReply struct {
	JsonTree             string   `protobuf:"bytes,1,opt,name=jsonTree,proto3" json:"jsonTree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTreeReply) Reset()         { *m = QueryTreeReply{} }
func (m *QueryTreeReply) String() string { return proto.CompactTextString(m) }
func (*QueryTreeReply) ProtoMessage()    {}
func (*QueryTreeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb732522b6cbe36, []int{4}
}

func (m *QueryTreeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTreeReply.Unmarshal(m, b)
}
func (m *QueryTreeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTreeReply.Marshal(b, m, deterministic)
}
func (m *QueryTreeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTreeReply.Merge(m, src)
}
func (m *QueryTreeReply) XXX_Size() int {
	return xxx_messageInfo_QueryTreeReply.Size(m)
}
func (m *QueryTreeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTreeReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTreeReply proto.InternalMessageInfo

func (m *QueryTreeReply) GetJsonTree() string {
	if m != nil {
		return m.JsonTree
	}
	return ""
}

///////////////////////////////////////////////////////////
type QueryProjectResRequest struct {
	ProjectID            int64    `protobuf:"varint,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryProjectResRequest) Reset()         { *m = QueryProjectResRequest{} }
func (m *QueryProjectResRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProjectResRequest) ProtoMessage()    {}
func (*QueryProjectResRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb732522b6cbe36, []int{5}
}

func (m *QueryProjectResRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProjectResRequest.Unmarshal(m, b)
}
func (m *QueryProjectResRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProjectResRequest.Marshal(b, m, deterministic)
}
func (m *QueryProjectResRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProjectResRequest.Merge(m, src)
}
func (m *QueryProjectResRequest) XXX_Size() int {
	return xxx_messageInfo_QueryProjectResRequest.Size(m)
}
func (m *QueryProjectResRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProjectResRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProjectResRequest proto.InternalMessageInfo

func (m *QueryProjectResRequest) GetProjectID() int64 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

type QueryProjectResReply struct {
	ProjectID            int64    `protobuf:"varint,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	CpuNodesAcquired     int64    `protobuf:"varint,2,opt,name=cpuNodesAcquired,proto3" json:"cpuNodesAcquired,omitempty"`
	GpuNodesAcquired     int64    `protobuf:"varint,3,opt,name=gpuNodesAcquired,proto3" json:"gpuNodesAcquired,omitempty"`
	StorageSizeAcquired  int64    `protobuf:"varint,4,opt,name=storageSizeAcquired,proto3" json:"storageSizeAcquired,omitempty"`
	CpuNodesArray        []int64  `protobuf:"varint,5,rep,packed,name=cpuNodesArray,proto3" json:"cpuNodesArray,omitempty"`
	CpuNodesStr          string   `protobuf:"bytes,6,opt,name=cpuNodesStr,proto3" json:"cpuNodesStr,omitempty"`
	GpuNodesArray        []int64  `protobuf:"varint,7,rep,packed,name=gpuNodesArray,proto3" json:"gpuNodesArray,omitempty"`
	GpuNodesStr          string   `protobuf:"bytes,8,opt,name=gpuNodesStr,proto3" json:"gpuNodesStr,omitempty"`
	StorageAllocInfo     string   `protobuf:"bytes,9,opt,name=storageAllocInfo,proto3" json:"storageAllocInfo,omitempty"`
	CreatedAt            string   `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryProjectResReply) Reset()         { *m = QueryProjectResReply{} }
func (m *QueryProjectResReply) String() string { return proto.CompactTextString(m) }
func (*QueryProjectResReply) ProtoMessage()    {}
func (*QueryProjectResReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb732522b6cbe36, []int{6}
}

func (m *QueryProjectResReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProjectResReply.Unmarshal(m, b)
}
func (m *QueryProjectResReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProjectResReply.Marshal(b, m, deterministic)
}
func (m *QueryProjectResReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProjectResReply.Merge(m, src)
}
func (m *QueryProjectResReply) XXX_Size() int {
	return xxx_messageInfo_QueryProjectResReply.Size(m)
}
func (m *QueryProjectResReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProjectResReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProjectResReply proto.InternalMessageInfo

func (m *QueryProjectResReply) GetProjectID() int64 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

func (m *QueryProjectResReply) GetCpuNodesAcquired() int64 {
	if m != nil {
		return m.CpuNodesAcquired
	}
	return 0
}

func (m *QueryProjectResReply) GetGpuNodesAcquired() int64 {
	if m != nil {
		return m.GpuNodesAcquired
	}
	return 0
}

func (m *QueryProjectResReply) GetStorageSizeAcquired() int64 {
	if m != nil {
		return m.StorageSizeAcquired
	}
	return 0
}

func (m *QueryProjectResReply) GetCpuNodesArray() []int64 {
	if m != nil {
		return m.CpuNodesArray
	}
	return nil
}

func (m *QueryProjectResReply) GetCpuNodesStr() string {
	if m != nil {
		return m.CpuNodesStr
	}
	return ""
}

func (m *QueryProjectResReply) GetGpuNodesArray() []int64 {
	if m != nil {
		return m.GpuNodesArray
	}
	return nil
}

func (m *QueryProjectResReply) GetGpuNodesStr() string {
	if m != nil {
		return m.GpuNodesStr
	}
	return ""
}

func (m *QueryProjectResReply) GetStorageAllocInfo() string {
	if m != nil {
		return m.StorageAllocInfo
	}
	return ""
}

func (m *QueryProjectResReply) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *QueryProjectResReply) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type QueryProjectResReplyLite struct {
	ProjectID            int64    `protobuf:"varint,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	CpuNodesAcquired     int64    `protobuf:"varint,2,opt,name=cpuNodesAcquired,proto3" json:"cpuNodesAcquired,omitempty"`
	GpuNodesAcquired     int64    `protobuf:"varint,3,opt,name=gpuNodesAcquired,proto3" json:"gpuNodesAcquired,omitempty"`
	StorageSizeAcquired  int64    `protobuf:"varint,4,opt,name=storageSizeAcquired,proto3" json:"storageSizeAcquired,omitempty"`
	StorageAllocInfo     string   `protobuf:"bytes,5,opt,name=storageAllocInfo,proto3" json:"storageAllocInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryProjectResReplyLite) Reset()         { *m = QueryProjectResReplyLite{} }
func (m *QueryProjectResReplyLite) String() string { return proto.CompactTextString(m) }
func (*QueryProjectResReplyLite) ProtoMessage()    {}
func (*QueryProjectResReplyLite) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb732522b6cbe36, []int{7}
}

func (m *QueryProjectResReplyLite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProjectResReplyLite.Unmarshal(m, b)
}
func (m *QueryProjectResReplyLite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProjectResReplyLite.Marshal(b, m, deterministic)
}
func (m *QueryProjectResReplyLite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProjectResReplyLite.Merge(m, src)
}
func (m *QueryProjectResReplyLite) XXX_Size() int {
	return xxx_messageInfo_QueryProjectResReplyLite.Size(m)
}
func (m *QueryProjectResReplyLite) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProjectResReplyLite.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProjectResReplyLite proto.InternalMessageInfo

func (m *QueryProjectResReplyLite) GetProjectID() int64 {
	if m != nil {
		return m.ProjectID
	}
	return 0
}

func (m *QueryProjectResReplyLite) GetCpuNodesAcquired() int64 {
	if m != nil {
		return m.CpuNodesAcquired
	}
	return 0
}

func (m *QueryProjectResReplyLite) GetGpuNodesAcquired() int64 {
	if m != nil {
		return m.GpuNodesAcquired
	}
	return 0
}

func (m *QueryProjectResReplyLite) GetStorageSizeAcquired() int64 {
	if m != nil {
		return m.StorageSizeAcquired
	}
	return 0
}

func (m *QueryProjectResReplyLite) GetStorageAllocInfo() string {
	if m != nil {
		return m.StorageAllocInfo
	}
	return ""
}

func init() {
	proto.RegisterType((*SchedulingCGpuRequest)(nil), "resScheduling.SchedulingCGpuRequest")
	proto.RegisterType((*SchedulingStorageRequest)(nil), "resScheduling.SchedulingStorageRequest")
	proto.RegisterType((*SchedulingReply)(nil), "resScheduling.SchedulingReply")
	proto.RegisterType((*QueryTreeRequest)(nil), "resScheduling.QueryTreeRequest")
	proto.RegisterType((*QueryTreeReply)(nil), "resScheduling.QueryTreeReply")
	proto.RegisterType((*QueryProjectResRequest)(nil), "resScheduling.QueryProjectResRequest")
	proto.RegisterType((*QueryProjectResReply)(nil), "resScheduling.QueryProjectResReply")
	proto.RegisterType((*QueryProjectResReplyLite)(nil), "resScheduling.QueryProjectResReplyLite")
}

func init() { proto.RegisterFile("scheduling.proto", fileDescriptor_9cb732522b6cbe36) }

var fileDescriptor_9cb732522b6cbe36 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x31, 0x0d, 0xf1, 0x54, 0x69, 0xc3, 0x96, 0x56, 0x2b, 0xab, 0x94, 0xc8, 0x14, 0x35,
	0x42, 0x28, 0x42, 0x80, 0xb8, 0x47, 0xad, 0x84, 0x22, 0xa1, 0x8a, 0x3a, 0x3d, 0x70, 0x02, 0x05,
	0x7b, 0x6a, 0x12, 0x59, 0xb1, 0xb3, 0x5e, 0x1f, 0xc2, 0xdb, 0xf0, 0x12, 0x3c, 0x04, 0xaf, 0x81,
	0xb8, 0xf2, 0x0c, 0x68, 0x77, 0xfd, 0x6f, 0x47, 0x31, 0xe2, 0x04, 0xc7, 0xfd, 0xe6, 0x9b, 0x6f,
	0x7e, 0x76, 0x76, 0x16, 0xfa, 0x91, 0xf3, 0x19, 0xdd, 0xd8, 0x9f, 0x2f, 0xbd, 0x51, 0xc8, 0x02,
	0x1e, 0x90, 0x1e, 0xc3, 0x68, 0x9a, 0x81, 0xd6, 0x57, 0x0d, 0x8e, 0xf2, 0xe3, 0xc5, 0x9b, 0x30,
	0xb6, 0x71, 0x15, 0x63, 0xc4, 0xc9, 0x09, 0x18, 0x21, 0x0b, 0x16, 0xe8, 0xf0, 0xc9, 0x25, 0xd5,
	0x06, 0xda, 0x50, 0xb7, 0x73, 0x80, 0x98, 0xd0, 0x75, 0xbc, 0x30, 0xbe, 0x59, 0x87, 0x48, 0xef,
	0x48, 0x63, 0x76, 0x26, 0xa7, 0x00, 0xcb, 0xc0, 0xc5, 0x68, 0x7c, 0xcb, 0x91, 0x51, 0x7d, 0xa0,
	0x0f, 0x75, 0xbb, 0x80, 0x90, 0x63, 0xe8, 0x38, 0x9c, 0xf9, 0x93, 0x4b, 0x7a, 0x57, 0x7a, 0x26,
	0xa7, 0x14, 0xbf, 0xb8, 0xa2, 0xbb, 0x03, 0x6d, 0x68, 0xd8, 0xc9, 0xc9, 0xfa, 0xae, 0x01, 0xcd,
	0x73, 0x9c, 0xf2, 0x80, 0xcd, 0x3c, 0x6c, 0x97, 0xe6, 0x53, 0xe8, 0x47, 0x8a, 0x3f, 0x9d, 0x7f,
	0x41, 0x95, 0x90, 0x4a, 0xb7, 0x86, 0x93, 0x57, 0x70, 0x94, 0x60, 0x63, 0xdf, 0x0f, 0x9c, 0xc9,
	0xf2, 0x36, 0x48, 0x2b, 0x10, 0xd9, 0x34, 0x1b, 0xff, 0xb8, 0x98, 0x9f, 0x1a, 0x1c, 0xe4, 0xc5,
	0xd8, 0x18, 0xfa, 0xeb, 0xed, 0x35, 0x38, 0x61, 0x7c, 0x25, 0xfb, 0xe7, 0xac, 0xe2, 0x39, 0x43,
	0x37, 0xad, 0xa1, 0x8a, 0x0b, 0xae, 0x57, 0xe5, 0xea, 0x8a, 0x5b, 0xc5, 0xc9, 0x73, 0x38, 0x2c,
	0xf6, 0x20, 0xa5, 0xab, 0x32, 0x9a, 0x4c, 0x85, 0x6e, 0x66, 0x4d, 0x48, 0xaa, 0xab, 0xe1, 0xd6,
	0x02, 0xfa, 0xd7, 0x31, 0xb2, 0xf5, 0x0d, 0x43, 0xfc, 0xfb, 0x91, 0x3a, 0x01, 0x63, 0x25, 0xd5,
	0x84, 0x51, 0x15, 0x94, 0x03, 0xd6, 0x33, 0xd8, 0x2f, 0xc4, 0x12, 0x1d, 0x35, 0xa1, 0xbb, 0x88,
	0x82, 0xa5, 0x00, 0x64, 0x20, 0xc3, 0xce, 0xce, 0xd6, 0x6b, 0x38, 0x96, 0xec, 0x77, 0x2a, 0xb2,
	0x8d, 0x51, 0xab, 0xfc, 0xac, 0x6f, 0x3a, 0x3c, 0xa8, 0x39, 0xfe, 0x4b, 0xd7, 0x77, 0x06, 0xbd,
	0x2c, 0x22, 0x63, 0xb3, 0x35, 0xdd, 0x95, 0x4f, 0xb3, 0x0c, 0x92, 0x01, 0xec, 0xa5, 0xc0, 0x94,
	0x33, 0xda, 0x91, 0xdd, 0x2b, 0x42, 0x42, 0xc7, 0x2b, 0xe9, 0xdc, 0x53, 0x3a, 0x5e, 0x55, 0xc7,
	0x2b, 0xe8, 0x74, 0x95, 0x4e, 0x01, 0x6a, 0x1c, 0x27, 0xa3, 0x79, 0x9c, 0x44, 0x8f, 0x1d, 0x86,
	0x33, 0x8e, 0xee, 0x98, 0x53, 0x90, 0xa4, 0x1c, 0x10, 0xd6, 0x38, 0x74, 0x13, 0xeb, 0x9e, 0xb2,
	0x66, 0x80, 0xf5, 0x4b, 0x03, 0xda, 0x74, 0x71, 0x6f, 0xe7, 0x1c, 0xff, 0xc7, 0xb7, 0xf7, 0xe2,
	0x87, 0x0e, 0x90, 0xef, 0x18, 0xf2, 0x1e, 0xf6, 0xcb, 0x2b, 0x9e, 0x9c, 0x8d, 0x4a, 0xbf, 0xc0,
	0xa8, 0xf1, 0x07, 0x30, 0x4f, 0x37, 0xb2, 0x64, 0xfb, 0xac, 0x1d, 0xf2, 0x01, 0xee, 0xd7, 0x16,
	0x33, 0x39, 0xdf, 0xe8, 0x56, 0x5e, 0xdd, 0x2d, 0xf4, 0xaf, 0xa1, 0x27, 0x2f, 0x4e, 0x64, 0x25,
	0xde, 0x2e, 0x79, 0x54, 0x71, 0xa9, 0xae, 0x18, 0xf3, 0xe1, 0x66, 0x82, 0x92, 0xfc, 0x08, 0x07,
	0x95, 0x59, 0x20, 0x4f, 0x9a, 0x7c, 0x6a, 0xdb, 0xc1, 0x7c, 0xbc, 0x8d, 0xa6, 0x02, 0x78, 0x70,
	0x58, 0xb1, 0xc8, 0x39, 0x6b, 0x19, 0xe4, 0xbc, 0x45, 0x10, 0xa1, 0x67, 0xed, 0x7c, 0xea, 0xc8,
	0x0f, 0xfd, 0xe5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0xb5, 0x2c, 0xad, 0xe4, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchedulingClient is the client API for Scheduling service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulingClient interface {
	// Scheduling Resource
	SchedulingCGpu(ctx context.Context, in *SchedulingCGpuRequest, opts ...grpc.CallOption) (*SchedulingReply, error)
	SchedulingStorage(ctx context.Context, in *SchedulingStorageRequest, opts ...grpc.CallOption) (*SchedulingReply, error)
	// Query Resource Tree
	QueryCGpuTree(ctx context.Context, in *QueryTreeRequest, opts ...grpc.CallOption) (*QueryTreeReply, error)
	// Query Project Resource
	QueryProjectRes(ctx context.Context, in *QueryProjectResRequest, opts ...grpc.CallOption) (*QueryProjectResReply, error)
	QueryProjectResLite(ctx context.Context, in *QueryProjectResRequest, opts ...grpc.CallOption) (*QueryProjectResReplyLite, error)
}

type schedulingClient struct {
	cc *grpc.ClientConn
}

func NewSchedulingClient(cc *grpc.ClientConn) SchedulingClient {
	return &schedulingClient{cc}
}

func (c *schedulingClient) SchedulingCGpu(ctx context.Context, in *SchedulingCGpuRequest, opts ...grpc.CallOption) (*SchedulingReply, error) {
	out := new(SchedulingReply)
	err := c.cc.Invoke(ctx, "/resScheduling.Scheduling/SchedulingCGpu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingClient) SchedulingStorage(ctx context.Context, in *SchedulingStorageRequest, opts ...grpc.CallOption) (*SchedulingReply, error) {
	out := new(SchedulingReply)
	err := c.cc.Invoke(ctx, "/resScheduling.Scheduling/SchedulingStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingClient) QueryCGpuTree(ctx context.Context, in *QueryTreeRequest, opts ...grpc.CallOption) (*QueryTreeReply, error) {
	out := new(QueryTreeReply)
	err := c.cc.Invoke(ctx, "/resScheduling.Scheduling/QueryCGpuTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingClient) QueryProjectRes(ctx context.Context, in *QueryProjectResRequest, opts ...grpc.CallOption) (*QueryProjectResReply, error) {
	out := new(QueryProjectResReply)
	err := c.cc.Invoke(ctx, "/resScheduling.Scheduling/QueryProjectRes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingClient) QueryProjectResLite(ctx context.Context, in *QueryProjectResRequest, opts ...grpc.CallOption) (*QueryProjectResReplyLite, error) {
	out := new(QueryProjectResReplyLite)
	err := c.cc.Invoke(ctx, "/resScheduling.Scheduling/QueryProjectResLite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingServer is the server API for Scheduling service.
type SchedulingServer interface {
	// Scheduling Resource
	SchedulingCGpu(context.Context, *SchedulingCGpuRequest) (*SchedulingReply, error)
	SchedulingStorage(context.Context, *SchedulingStorageRequest) (*SchedulingReply, error)
	// Query Resource Tree
	QueryCGpuTree(context.Context, *QueryTreeRequest) (*QueryTreeReply, error)
	// Query Project Resource
	QueryProjectRes(context.Context, *QueryProjectResRequest) (*QueryProjectResReply, error)
	QueryProjectResLite(context.Context, *QueryProjectResRequest) (*QueryProjectResReplyLite, error)
}

// UnimplementedSchedulingServer can be embedded to have forward compatible implementations.
type UnimplementedSchedulingServer struct {
}

func (*UnimplementedSchedulingServer) SchedulingCGpu(ctx context.Context, req *SchedulingCGpuRequest) (*SchedulingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SchedulingCGpu not implemented")
}
func (*UnimplementedSchedulingServer) SchedulingStorage(ctx context.Context, req *SchedulingStorageRequest) (*SchedulingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SchedulingStorage not implemented")
}
func (*UnimplementedSchedulingServer) QueryCGpuTree(ctx context.Context, req *QueryTreeRequest) (*QueryTreeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryCGpuTree not implemented")
}
func (*UnimplementedSchedulingServer) QueryProjectRes(ctx context.Context, req *QueryProjectResRequest) (*QueryProjectResReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryProjectRes not implemented")
}
func (*UnimplementedSchedulingServer) QueryProjectResLite(ctx context.Context, req *QueryProjectResRequest) (*QueryProjectResReplyLite, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryProjectResLite not implemented")
}

func RegisterSchedulingServer(s *grpc.Server, srv SchedulingServer) {
	s.RegisterService(&_Scheduling_serviceDesc, srv)
}

func _Scheduling_SchedulingCGpu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulingCGpuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).SchedulingCGpu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resScheduling.Scheduling/SchedulingCGpu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).SchedulingCGpu(ctx, req.(*SchedulingCGpuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduling_SchedulingStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulingStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).SchedulingStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resScheduling.Scheduling/SchedulingStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).SchedulingStorage(ctx, req.(*SchedulingStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduling_QueryCGpuTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).QueryCGpuTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resScheduling.Scheduling/QueryCGpuTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).QueryCGpuTree(ctx, req.(*QueryTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduling_QueryProjectRes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProjectResRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).QueryProjectRes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resScheduling.Scheduling/QueryProjectRes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).QueryProjectRes(ctx, req.(*QueryProjectResRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduling_QueryProjectResLite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProjectResRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).QueryProjectResLite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resScheduling.Scheduling/QueryProjectResLite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).QueryProjectResLite(ctx, req.(*QueryProjectResRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduling_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resScheduling.Scheduling",
	HandlerType: (*SchedulingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SchedulingCGpu",
			Handler:    _Scheduling_SchedulingCGpu_Handler,
		},
		{
			MethodName: "SchedulingStorage",
			Handler:    _Scheduling_SchedulingStorage_Handler,
		},
		{
			MethodName: "QueryCGpuTree",
			Handler:    _Scheduling_QueryCGpuTree_Handler,
		},
		{
			MethodName: "QueryProjectRes",
			Handler:    _Scheduling_QueryProjectRes_Handler,
		},
		{
			MethodName: "QueryProjectResLite",
			Handler:    _Scheduling_QueryProjectResLite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduling.proto",
}
